#!/usr/bin/env node
// Generate backend/seed.sql from the existing /data JSON packs so the D1
// database starts with the full current catalog (3,599 cards).
//
// Usage: node scripts/build_seed.mjs   (or: npm run build:seed)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.resolve(HERE, '../../data');
const OUT = path.resolve(HERE, '../seed.sql');
// Keep each INSERT well under D1's ~100 KB per-statement limit.
const ROWS_PER_INSERT = 25;
// Fields promoted to their own columns — drop them from the `data` JSON blob.
const PROMOTED_FIELDS = ['id', 'type', 'band', 'rank', 'spanish', 'english', 'partOfSpeech'];

const readJson = (name) => JSON.parse(fs.readFileSync(path.join(DATA, name), 'utf8'));

const pack = readJson('guatemala_spanish_study_pack.json');
const synonyms = readJson('synonyms.json');
const sentences = readJson('sentences.json');

// Choose the best example sentence for a card (mirrors the client's sentenceFor).
function sentenceFor(deckId, es, entry) {
  if (deckId === 'mainWords') {
    if (sentences[es]) return { es: sentences[es].es, en: sentences[es].en || '' };
    if (entry.miniPhrase) return { es: entry.miniPhrase, en: entry.miniPhraseEnglish || '' };
    return null;
  }
  if (deckId === 'guatemalaLexicon' && entry.lexiconExampleEs) {
    return { es: entry.lexiconExampleEs, en: entry.lexiconExampleEn || '' };
  }
  return null;
}

const sqlStr = (value) => {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
};
const sqlNum = (value) => (Number.isFinite(value) ? String(value) : 'NULL');

const now = Date.now();
const rows = [];

for (const [deckId, entries] of Object.entries(pack.collections || {})) {
  for (const entry of entries) {
    const es = entry.spanish || '';
    const syns = deckId === 'mainWords' ? synonyms[es] || [] : [];
    const sentence = sentenceFor(deckId, es, entry);
    // Preserve deck-specific extras (context/focus/note/lexicon fields, etc.),
    // dropping anything already stored in its own column.
    const data = { ...entry };
    for (const key of PROMOTED_FIELDS) delete data[key];

    rows.push([
      sqlStr(entry.id),
      sqlStr(deckId),
      sqlStr(entry.type || 'word'),
      sqlStr(entry.band || null),
      sqlNum(entry.rank),
      sqlStr(es),
      sqlStr(entry.english || ''),
      sqlStr(entry.partOfSpeech || null),
      sqlStr(JSON.stringify(syns)),
      sqlStr(sentence ? sentence.es : null),
      sqlStr(sentence ? sentence.en : null),
      sqlStr(JSON.stringify(data)),
      String(now),
      String(now),
    ]);
  }
}

const columns =
  '(id, deck, type, band, rank, es, en, pos, synonyms, sentence_es, sentence_en, data, created_at, updated_at)';

const parts = [
  '-- Generated by scripts/build_seed.mjs — do not edit by hand.',
  '-- Loads the full current catalog into the words table.',
  'DELETE FROM words;',
  '',
];

for (let i = 0; i < rows.length; i += ROWS_PER_INSERT) {
  const chunk = rows.slice(i, i + ROWS_PER_INSERT);
  const values = chunk.map((cells) => `(${cells.join(', ')})`).join(',\n');
  parts.push(`INSERT INTO words ${columns} VALUES\n${values};`);
}

fs.writeFileSync(OUT, parts.join('\n') + '\n', 'utf8');
console.log(`Wrote ${OUT} with ${rows.length} words in ${Math.ceil(rows.length / ROWS_PER_INSERT)} INSERT statements.`);
